### ISSUE TITLE
Failed to build on pypy : msgspec (0.16.0) not supporting PEP 517 builds. 

### ISSUE THREAD

**Issue by v3ss0n** [jcrist/msgspec#443]
### Description

msgspec fails to build and stuck on pypy , version pypy-3.10-v7.3.12

`  gcc -pthread -DNDEBUG -O2 -fPIC -I/tmp/tmplro65bau/.venv/include -I/home/nozander/pypy/include/pypy3.10 -c msgspec/_core.c -o build/temp.linux-x86_64-pypy310/msgspec/_core.o `

Step

```py
  msgspec/_core.c: In function ‘json_decode_list’:
  msgspec/_core.c:58:46: error: ‘PyListObject’ has no member named ‘allocated’
     58 | #define LIST_CAPACITY(x) (((PyListObject *)x)->allocated)
        |                                              ^~
  msgspec/common.h:5:45: note: in definition of macro ‘MS_LIKELY’
      5 | #define MS_LIKELY(pred) __builtin_expect(!!(pred), 1)
        |                                             ^~~~
  msgspec/_core.c:14694:24: note: in expansion of macro ‘LIST_CAPACITY’
  14694 |         if (MS_LIKELY((LIST_CAPACITY(out) > Py_SIZE(out)))) {
        |                        ^~~~~~~~~~~~~
  error: command '/usr/bin/gcc' failed with exit code 1
  

  at .env/lib/pypy3.10/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with msgspec (0.16.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "msgspec (==0.16.0)"'.
```

**Comment by jcrist** [comment]
msgspec does not support pypy. See #22.
