### ISSUE TITLE
Python 3.14 first parameter lost on initialisation

### ISSUE THREAD

**Issue by mosquito** [jcrist/msgspec#924]
### Description

On python 3.14 I trying to run simple code, but it fails:

```python
from msgspec import Struct


class MsgSpec(Struct):
    id: int
    method: str
    params: dict[str, str]


if __name__ == "__main__":
    MsgSpec(id=1, method="test", params={"key": "value"})
```

When i trying to run it:

```
python3.14 msgspec_3.14.py 
Traceback (most recent call last):
  File "msgspec_3.14.py", line 12, in <module>
    MsgSpec(id=1, method="test", params={"key": "value"})
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Unexpected keyword argument 'id'
```

Under `python<3.14` it is ok.

**Comment by provinzkraut** [comment]
What msgspec version are you using? `0.19.0` does not currently support `3.14` properly.

**Comment by kamikaze** [comment]
Pydantic works fine with 3.14

**Comment by provinzkraut** [comment]
> Pydantic works fine with 3.14

This is msgspec, not Pydantic, so I don't see how that's relevant?

**Comment by mosquito** [comment]
I use `0.19.0` it is latest version, sorry my bad, I should have define it in description

**Comment by provinzkraut** [comment]
As I wrote earlier, that version is not compatible with Pyhton 3.14. Can you try installing msgspec from `main` and confirm the issue does not exist for you with that version?

**Comment by mosquito** [comment]
I saw some constants [here](https://github.com/jcrist/msgspec/blob/0.19.0/msgspec/_core.c#L23), I thought python 3.14 already supported.

**Comment by provinzkraut** [comment]
It is not. See #891

**Comment by nhumrich** [comment]
I was able to get msgspec working on 3.14 by adding:
`from __future__ import annotation` to all my files that import Struct, if that's worth anything to anyone.

**Comment by ofek** [comment]
https://github.com/jcrist/msgspec/releases/tag/0.20.0
